//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBanHangMeatDeli.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Orders
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_Orders()
        {
            this.tb_OrderDetails = new HashSet<tb_OrderDetails>();
        }
    
        public int Id { get; set; }
        public string Code { get; set; }
        public Nullable<int> User_Id { get; set; }
        public string Phone { get; set; }
        public string Address { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public Nullable<int> Quantity { get; set; }
        public string CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public string ModifiedDate { get; set; }
        public string ModifiedBy { get; set; }
        public string NameOrder { get; set; }
        public string Email { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_OrderDetails> tb_OrderDetails { get; set; }
        public virtual tb_Users tb_Users { get; set; }
    }
}
